language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install --yes bzr bzrtools git mercurial
install:
  - pip install pip-accel
  - pip-accel install coveralls
  - pip-accel install --requirement=requirements-checks.txt
  - pip-accel install --requirement=requirements-tests.txt
  - LC_ALL=C pip-accel install .
script:
  - make check
  - make test
after_success:
  - coveralls
branches:
  except:
    - /^[0-9]/
